[package]
name = "irisui"
description = "GPU-accelerated Retained-Mode UI framework for games and creative software"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
iris-core = { workspace = true }
iris-layout = { workspace = true }
iris-text = { workspace = true }
iris-wgpu = { workspace = true }
iris-widgets = { workspace = true }
iris-dock = { workspace = true }
