[workspace]
members = [
    "crates/ae_core",
    "crates/ae_renderer",
    "crates/ae_plugin_api",
    "crates/ae_plugin_host",
    "crates/ae_editor",
    "crates/ae_editor_ui",
    "crates/game_logic",
    "crates/ae_physics",
    "crates/ae_audio",
    "crates/ae_texture",
    "crates/ae_animation",
    "crates/ae_uidesign",
    "crates/ae_engine",
]
resolver = "2"

[patch.crates-io]
wgpu = { git = "https://github.com/aethelisdev/aeongpu.git", branch = "aeon-v30" }
wgpu-core = { git = "https://github.com/aethelisdev/aeongpu.git", branch = "aeon-v30" }
wgpu-hal = { git = "https://github.com/aethelisdev/aeongpu.git", branch = "aeon-v30" }
wgpu-types = { git = "https://github.com/aethelisdev/aeongpu.git", branch = "aeon-v30" }
naga = { git = "https://github.com/aethelisdev/aeongpu.git", branch = "aeon-v30" }
