[package]
name = "ae_renderer"
version = "0.7.0"
edition = "2024"
description = "Aeon Engine - WGPU rendering pipeline"

[dependencies]
winit = "0.30.13"
wgpu = "30.0.0"
log = "0.4.33"
bytemuck = { version = "1.25.0", features = ["derive"] }
cgmath = "0.18"
image = "0.25.10"
gltf = "1.4.1"
serde = { version = "1.0.228", features = ["derive"] }
slotmap = { version = "1.1.1", features = ["serde"] }
rayon = "1.12.0"
hecs = "0.11.0"
glam = "0.33.0"
ae_core = { path = "../ae_core" }
ae_plugin_api = { path = "../ae_plugin_api" }
ae_texture = { path = "../ae_texture" }
ae_animation = { path = "../ae_animation" }



