// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 AethelisDEV / Aeon Engine. All rights reserved.

//! # Settings and Preferences Data Models & Style Descriptors
//!
//! Provides geometric frames, visual style presets, and tab specifications
//! for building tabbed modal preference dialogs, collapsible sections, and setting rows.

use iris_core::color::Color;
use iris_core::geometry::Rect;
use iris_core::id::WidgetId;

/// Visual styling configuration for a multi-tab preference dialog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TabbedDialogStyle {
    /// Background color of the main dialog window card.
    pub card_bg: Color,
    /// Border color of the main dialog window card.
    pub card_border_color: Color,
    /// Border width of the main dialog window card in logical pixels.
    pub card_border_width: f32,
    /// Corner rounding radius of the main dialog window card.
    pub card_border_radius: f32,
    /// Height of the top titlebar header in logical pixels.
    pub titlebar_height: f32,
    /// Background color of the top titlebar header.
    pub titlebar_bg: Color,
    /// Border color of the titlebar header bottom divider.
    pub titlebar_border_color: Color,
    /// Title text label color.
    pub title_color: Color,
    /// Background color of the left navigation sidebar.
    pub sidebar_bg: Color,
    /// Border color of the vertical sidebar divider.
    pub sidebar_divider_color: Color,
    /// Default background color of an unselected sidebar tab item.
    pub tab_bg_idle: Color,
    /// Background color of a hovered sidebar tab item.
    pub tab_bg_hover: Color,
    /// Background color of the actively selected sidebar tab item.
    pub tab_bg_selected: Color,
    /// Text color of an unselected sidebar tab label.
    pub tab_text_idle: Color,
    /// Text color of a hovered sidebar tab label.
    pub tab_text_hover: Color,
    /// Text color of the actively selected sidebar tab label.
    pub tab_text_selected: Color,
    /// Color of the active tab selection indicator accent line.
    pub tab_indicator_color: Color,
    /// Normal background color of the titlebar close button.
    pub close_btn_bg_idle: Color,
    /// Hovered background color of the titlebar close button.
    pub close_btn_bg_hover: Color,
    /// Text color of the close button glyph ('✖').
    pub close_btn_text_color: Color,
}

impl Default for TabbedDialogStyle {
    fn default() -> Self {
        Self {
            card_bg: Color::rgba(0.08, 0.09, 0.12, 0.98),
            card_border_color: Color::rgba(0.22, 0.25, 0.35, 1.0),
            card_border_width: 1.0,
            card_border_radius: 8.0,
            titlebar_height: 36.0,
            titlebar_bg: Color::rgba(0.06, 0.07, 0.09, 1.0),
            titlebar_border_color: Color::rgba(0.18, 0.20, 0.28, 0.90),
            title_color: Color::rgba(0.90, 0.92, 0.96, 1.0),
            sidebar_bg: Color::rgba(0.07, 0.08, 0.10, 0.95),
            sidebar_divider_color: Color::rgba(0.18, 0.20, 0.28, 0.90),
            tab_bg_idle: Color::rgba(0.0, 0.0, 0.0, 0.0),
            tab_bg_hover: Color::rgba(0.12, 0.14, 0.19, 1.0),
            tab_bg_selected: Color::rgba(0.0, 0.24, 0.31, 0.70),
            tab_text_idle: Color::rgba(0.65, 0.68, 0.76, 1.0),
            tab_text_hover: Color::rgba(1.0, 1.0, 1.0, 1.0),
            tab_text_selected: Color::rgba(0.0, 0.90, 1.0, 1.0),
            tab_indicator_color: Color::rgba(0.0, 0.90, 1.0, 1.0),
            close_btn_bg_idle: Color::rgba(0.0, 0.0, 0.0, 0.0),
            close_btn_bg_hover: Color::rgba(0.85, 0.20, 0.20, 0.85),
            close_btn_text_color: Color::rgba(0.65, 0.68, 0.76, 1.0),
        }
    }
}

/// Specification of an individual sidebar navigation tab item.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TabbedDialogTab<'a> {
    /// Human-readable label of the tab.
    pub label: &'a str,
    /// Unique integer identifier for active tab routing.
    pub id: u8,
}

impl<'a> TabbedDialogTab<'a> {
    /// Creates a new tab specification.
    #[inline]
    pub const fn new(label: &'a str, id: u8) -> Self {
        Self { label, id }
    }
}

/// Structural frame targets generated by [`super::dialog::TabbedDialogBuilder`].
#[derive(Debug, Clone, PartialEq)]
pub struct TabbedDialogFrame {
    /// Root modal window card node ID.
    pub card_id: WidgetId,
    /// Draggable titlebar node ID.
    pub titlebar_id: WidgetId,
    /// Bounding rectangle of the draggable titlebar.
    pub titlebar_rect: Rect,
    /// Bounding rectangle of the close button.
    pub close_btn_rect: Rect,
    /// Content area container node ID (has `clip_children: true`).
    pub content_id: WidgetId,
    /// Bounding rectangle of the right content area.
    pub content_rect: Rect,
    /// Bounding rectangles and IDs of each sidebar tab.
    pub tab_rects: Vec<(u8, Rect)>,
}

/// Visual styling configuration for a collapsible settings section group card.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SettingSectionStyle {
    /// Background color of the section group card.
    pub bg_color: Color,
    /// Border color of the section group card.
    pub border_color: Color,
    /// Border width in logical pixels.
    pub border_width: f32,
    /// Corner rounding radius of the card capsule.
    pub border_radius: f32,
    /// Normal title text color.
    pub title_color_idle: Color,
    /// Hovered title text color.
    pub title_color_hover: Color,
    /// Header font size in logical points.
    pub title_font_size: f32,
    /// Description subtitle text color.
    pub description_color: Color,
    /// Description font size in logical points.
    pub description_font_size: f32,
}

impl Default for SettingSectionStyle {
    fn default() -> Self {
        Self {
            bg_color: Color::rgba(0.09, 0.10, 0.14, 0.85),
            border_color: Color::rgba(0.18, 0.20, 0.28, 0.90),
            border_width: 1.0,
            border_radius: 6.0,
            title_color_idle: Color::rgba(0.88, 0.91, 0.96, 1.0),
            title_color_hover: Color::WHITE,
            title_font_size: 13.0,
            description_color: Color::rgba(0.60, 0.63, 0.72, 1.0),
            description_font_size: 11.0,
        }
    }
}

/// Structural frame targets generated by [`super::section::SettingSectionBuilder`].
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SettingSectionFrame {
    /// Container card node ID.
    pub card_id: WidgetId,
    /// Interactive header toggle hit target rectangle.
    pub header_rect: Rect,
    /// Y coordinate offset inside the content area for subsequent child items.
    pub content_start_y: f32,
    /// Total computed height of the section card in logical pixels.
    pub total_height: f32,
}