// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 AethelisDEV / Aeon Engine. All rights reserved.

//! # Console & Logger Iris UI Types
//!
//! Type definitions, filtering modes, parameters, and interactive targets
//! for the hardware-accelerated Developer Console panel.
//!

use crate::ui::types::ConsoleEntry;
use irisui::prelude::{Point, Rect};

pub use irisui::prelude::ConsoleFilterLevel;

/// Extension methods for `ConsoleFilterLevel` log matching.
pub trait ConsoleFilterExt {
    /// Checks if a log entry matches the current filter level.
    fn matches(&self, level: log::Level) -> bool;
}

impl ConsoleFilterExt for ConsoleFilterLevel {
    fn matches(&self, level: log::Level) -> bool {
        match self {
            Self::All => true,
            Self::Error => level == log::Level::Error,
            Self::Warn => level == log::Level::Warn,
            Self::Info => level == log::Level::Info,
            Self::Debug => level == log::Level::Debug || level == log::Level::Trace,
        }
    }
}

/// Parameters passed to the Developer Console layout builder.
pub struct ConsolePanelParams<'a> {
    /// Bounding rectangle allocated for the docked console panel.
    pub panel_rect: Rect,
    /// Slice of active in-memory log entries.
    pub entries: &'a [ConsoleEntry],
    /// Current vertical scroll offset in physical pixels.
    pub scroll_y: f32,
    /// Active log severity filter.
    pub filter: ConsoleFilterLevel,
    /// Substring search query for filtering log targets and messages.
    pub search_query: &'a str,
    /// Whether the search input box currently has keyboard focus.
    pub is_search_focused: bool,
    /// Whether the console automatically scrolls down when new logs arrive.
    pub auto_scroll: bool,
    /// Current cursor position for hover detection.
    pub cursor_pos: Point,
    /// Caret blink phase indicator for text inputs.
    pub blink_caret: bool,
}

/// Interactive click and hover targets registered during console layout construction.
///
/// Note: Toolbar buttons and filters are resolved via semantic tags and `UiTree::hit_test_target`.
#[derive(Clone, Debug, Default)]
pub struct ConsolePanelTargets {
    /// Bounding box of the complete console panel.
    pub panel_rect: Rect,
    /// Bounding box of the search input field.
    pub search_input_rect: Rect,
    /// Bounding box of the scrollable log entries viewport.
    pub rows_viewport_rect: Rect,
    /// Total computed height of all filtered log rows.
    pub total_content_height: f32,
    /// Maximum vertical scroll offset.
    pub max_scroll_y: f32,
}

/// Action generated by user interaction with the Developer Console.
#[derive(Clone, Debug, PartialEq)]
pub enum ConsoleAction {
    /// Clears all stored logs in the logger subsystem.
    ClearLogs,
    /// Updates the active log filter level.
    SetFilter(ConsoleFilterLevel),
    /// Toggles the automatic scroll-to-bottom behavior.
    ToggleAutoScroll,
    /// Sets keyboard focus to the search query field.
    FocusSearch,
    /// Clears the active search filter query.
    ClearSearch,
    /// Copies a specific log message string to the clipboard.
    CopyLog(String),
}

/// Persistent interactive state for the Developer Console panel overlay.
#[derive(Debug, Clone)]
pub struct ConsolePanelState {
    /// Common panel interaction state (targets, scroll_y, search, actions).
    pub interactions:
        crate::ui::iris_bridge::types::PanelInteractionState<ConsolePanelTargets, ConsoleAction>,
    /// Active log level severity filter.
    pub filter: ConsoleFilterLevel,
    /// Whether Developer Console automatically scrolls down when new logs arrive.
    pub auto_scroll: bool,
}

impl Default for ConsolePanelState {
    fn default() -> Self {
        Self {
            interactions: crate::ui::iris_bridge::types::PanelInteractionState::default(),
            filter: ConsoleFilterLevel::All,
            auto_scroll: true,
        }
    }
}

impl std::ops::Deref for ConsolePanelState {
    type Target =
        crate::ui::iris_bridge::types::PanelInteractionState<ConsolePanelTargets, ConsoleAction>;
    fn deref(&self) -> &Self::Target {
        &self.interactions
    }
}

impl std::ops::DerefMut for ConsolePanelState {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.interactions
    }
}