// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 AethelisDEV / Aeon Engine. All rights reserved.

//! # Console & Logger Iris UI Types
//!
//! Type definitions, filtering modes, parameters, and interactive targets
//! for the hardware-accelerated Developer Console panel.
//!

use crate::ui::types::ConsoleEntry;
use irisui::prelude::{Point, Rect};

/// Log level filter modes for the Developer Console.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum ConsoleFilterLevel {
    /// Display all log messages without severity filtering.
    #[default]
    All,
    /// Display only error messages.
    Error,
    /// Display only warning messages.
    Warn,
    /// Display only informational messages.
    Info,
    /// Display only debug messages.
    Debug,
}

impl ConsoleFilterLevel {
    /// Returns the human-readable label for the filter button.
    pub fn label(&self) -> &'static str {
        match self {
            Self::All => "All",
            Self::Error => "Errors",
            Self::Warn => "Warnings",
            Self::Info => "Info",
            Self::Debug => "Debug",
        }
    }

    /// Checks if a log entry matches the current filter level.
    pub fn matches(&self, level: log::Level) -> bool {
        match self {
            Self::All => true,
            Self::Error => level == log::Level::Error,
            Self::Warn => level == log::Level::Warn,
            Self::Info => level == log::Level::Info,
            Self::Debug => level == log::Level::Debug || level == log::Level::Trace,
        }
    }
}

/// Parameters passed to the Developer Console layout builder.
pub struct ConsolePanelParams<'a> {
    /// Bounding rectangle allocated for the docked console panel.
    pub panel_rect: Rect,
    /// Slice of active in-memory log entries.
    pub entries: &'a [ConsoleEntry],
    /// Current vertical scroll offset in physical pixels.
    pub scroll_y: f32,
    /// Active log severity filter.
    pub filter: ConsoleFilterLevel,
    /// Substring search query for filtering log targets and messages.
    pub search_query: &'a str,
    /// Whether the search input box currently has keyboard focus.
    pub is_search_focused: bool,
    /// Whether the console automatically scrolls down when new logs arrive.
    pub auto_scroll: bool,
    /// Current cursor position for hover detection.
    pub cursor_pos: Point,
    /// Caret blink phase indicator for text inputs.
    pub blink_caret: bool,
}

/// Interactive click and hover targets registered during console layout construction.
#[derive(Clone, Debug, Default)]
pub struct ConsolePanelTargets {
    /// Bounding box of the complete console panel.
    pub panel_rect: Rect,
    /// Bounding box of the "Clear Logs" button.
    pub clear_btn_rect: Rect,
    /// Bounding box of the "All" filter button.
    pub filter_all_rect: Rect,
    /// Bounding box of the "Errors" filter button.
    pub filter_error_rect: Rect,
    /// Bounding box of the "Warnings" filter button.
    pub filter_warn_rect: Rect,
    /// Bounding box of the "Info" filter button.
    pub filter_info_rect: Rect,
    /// Bounding box of the "Debug" filter button.
    pub filter_debug_rect: Rect,
    /// Bounding box of the "Auto-Scroll" toggle.
    pub autoscroll_toggle_rect: Rect,
    /// Bounding box of the search input field.
    pub search_input_rect: Rect,
    /// Optional bounding box of the search clear "✖" button.
    pub search_clear_btn_rect: Option<Rect>,
    /// Bounding box of the scrollable log entries viewport.
    pub rows_viewport_rect: Rect,
    /// Total computed height of all filtered log rows.
    pub total_content_height: f32,
    /// Maximum vertical scroll offset.
    pub max_scroll_y: f32,
}

/// Action generated by user interaction with the Developer Console.
#[derive(Clone, Debug, PartialEq)]
pub enum ConsoleAction {
    /// Clears all stored logs in the logger subsystem.
    ClearLogs,
    /// Updates the active log filter level.
    SetFilter(ConsoleFilterLevel),
    /// Toggles the automatic scroll-to-bottom behavior.
    ToggleAutoScroll,
    /// Sets keyboard focus to the search query field.
    FocusSearch,
    /// Clears the active search filter query.
    ClearSearch,
    /// Copies a specific log message string to the clipboard.
    CopyLog(String),
}