// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 AethelisDEV / Aeon Engine. All rights reserved.

//! # Console & Logger Iris UI Types
//!
//! Type definitions, filtering modes, parameters, semantic tags, and hit-testing
//! resolvers for the hardware-accelerated Developer Console panel.
//!

use crate::ui::types::ConsoleEntry;
use irisui::prelude::{Point, Rect, UiTree, WidgetRole};

/// Semantic hit-testing tag for the Developer Console root panel container.
pub const CONSOLE_TAG_PANEL_ROOT: u64 = 0x5000;

/// Semantic hit-testing tag for the "Clear Logs" toolbar button.
pub const CONSOLE_TAG_CLEAR: u64 = 0x5001;

/// Semantic hit-testing tag for the "All" severity filter button.
pub const CONSOLE_TAG_FILTER_ALL: u64 = 0x5002;

/// Semantic hit-testing tag for the "Errors" severity filter button.
pub const CONSOLE_TAG_FILTER_ERROR: u64 = 0x5003;

/// Semantic hit-testing tag for the "Warnings" severity filter button.
pub const CONSOLE_TAG_FILTER_WARN: u64 = 0x5004;

/// Semantic hit-testing tag for the "Info" severity filter button.
pub const CONSOLE_TAG_FILTER_INFO: u64 = 0x5005;

/// Semantic hit-testing tag for the "Debug" severity filter button.
pub const CONSOLE_TAG_FILTER_DEBUG: u64 = 0x5006;

/// Semantic hit-testing tag for the "Auto-Scroll" toggle button.
pub const CONSOLE_TAG_AUTOSCROLL: u64 = 0x5007;

/// Semantic hit-testing tag for the search clear "✖" button.
pub const CONSOLE_TAG_SEARCH_CLEAR: u64 = 0x5008;

/// Semantic hit-testing tag for the search text input field.
pub const CONSOLE_TAG_SEARCH_INPUT: u64 = 0x5009;

/// Semantic hit-testing tag for the Developer Console toolbar container.
pub const CONSOLE_TAG_TOOLBAR: u64 = 0x500a;

/// Semantic hit-testing tag for the Developer Console scrollable logs viewport.
pub const CONSOLE_TAG_VIEWPORT: u64 = 0x500b;

/// Semantic hit-testing tag for individual Developer Console log entry rows.
pub const CONSOLE_TAG_ROW: u64 = 0x500c;

/// Semantic hit-testing tag for the Developer Console scrollbar track.
pub const CONSOLE_TAG_SCROLLBAR_TRACK: u64 = 0x500d;

/// Semantic hit-testing tag for the Developer Console scrollbar thumb.
pub const CONSOLE_TAG_SCROLLBAR_THUMB: u64 = 0x500e;

/// Determines whether the given semantic hit-testing tag belongs to the Developer Console subsystem.
///
/// Returns `true` if `tag` falls within the Developer Console tag range (`0x5000..=0x50ff`).
#[inline]
#[must_use]
pub const fn is_console_tag(tag: u64) -> bool {
    tag >= 0x5000 && tag <= 0x50ff
}

/// Log severity filter levels supported by the Developer Console.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum ConsoleFilterLevel {
    /// Display all log messages without severity filtering.
    #[default]
    All,
    /// Display only error messages.
    Error,
    /// Display only warning messages.
    Warn,
    /// Display only informational messages.
    Info,
    /// Display only debug messages.
    Debug,
}

impl ConsoleFilterLevel {
    /// Returns the human-readable display label for the filter button.
    #[must_use]
    pub const fn label(&self) -> &'static str {
        match self {
            Self::All => "All",
            Self::Error => "Errors",
            Self::Warn => "Warnings",
            Self::Info => "Info",
            Self::Debug => "Debug",
        }
    }
}

/// Extension methods for `ConsoleFilterLevel` log matching.
pub trait ConsoleFilterExt {
    /// Checks if a log entry matches the current filter level.
    fn matches(&self, level: log::Level) -> bool;
}

impl ConsoleFilterExt for ConsoleFilterLevel {
    fn matches(&self, level: log::Level) -> bool {
        match self {
            Self::All => true,
            Self::Error => level == log::Level::Error,
            Self::Warn => level == log::Level::Warn,
            Self::Info => level == log::Level::Info,
            Self::Debug => level == log::Level::Debug || level == log::Level::Trace,
        }
    }
}

/// Unified action generated by user interaction with the Developer Console.
#[derive(Clone, Debug, PartialEq)]
pub enum ConsoleAction {
    /// Clears all stored logs in the logger subsystem.
    ClearLogs,
    /// Updates the active log filter level.
    SetFilter(ConsoleFilterLevel),
    /// Toggles the automatic scroll-to-bottom behavior.
    ToggleAutoScroll,
    /// Sets keyboard focus to the search query field.
    FocusSearch,
    /// Clears the active search filter query.
    ClearSearch,
    /// Copies a specific log message string to the clipboard.
    CopyLog(String),
}

/// Cursor icon hints for console interactive hover targets.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConsoleToolbarCursor {
    /// Interactive click target (button, filter tab, clear toggle).
    Pointer,
    /// Editable text input field.
    Text,
}

/// Severity level representation for individual console log entries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum ConsoleLogLevel {
    /// Severe error condition or unrecoverable subsystem failure.
    Error,
    /// Non-fatal warning or unexpected state.
    Warn,
    /// Informational status milestone or progress message.
    #[default]
    Info,
    /// Detailed diagnostic debug trace.
    Debug,
    /// Fine-grained internal execution trace.
    Trace,
}

/// Aggregated log entry counts per severity level for display in toolbar badges.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ConsoleLogCounts {
    /// Total count of all log entries across all severity levels.
    pub all: usize,
    /// Count of log entries with `Error` severity.
    pub error: usize,
    /// Count of log entries with `Warn` severity.
    pub warn: usize,
    /// Count of log entries with `Info` severity.
    pub info: usize,
    /// Count of log entries with `Debug` or `Trace` severity.
    pub debug: usize,
}

impl ConsoleLogCounts {
    /// Creates a new log count descriptor with all fields explicitly initialized.
    #[inline]
    #[must_use]
    pub const fn new(all: usize, error: usize, warn: usize, info: usize, debug: usize) -> Self {
        Self {
            all,
            error,
            warn,
            info,
            debug,
        }
    }
}

/// Evaluates a mouse click coordinate against the semantic `UiTree` to resolve console toolbar actions.
///
/// Returns `Some(ConsoleAction)` if the click position hits a recognized console toolbar element.
pub fn evaluate_console_toolbar_click(tree: &UiTree, click_pos: Point) -> Option<ConsoleAction> {
    let hit = tree.hit_test_target(click_pos)?;
    match hit.tag {
        CONSOLE_TAG_CLEAR => Some(ConsoleAction::ClearLogs),
        CONSOLE_TAG_FILTER_ALL => Some(ConsoleAction::SetFilter(ConsoleFilterLevel::All)),
        CONSOLE_TAG_FILTER_ERROR => Some(ConsoleAction::SetFilter(ConsoleFilterLevel::Error)),
        CONSOLE_TAG_FILTER_WARN => Some(ConsoleAction::SetFilter(ConsoleFilterLevel::Warn)),
        CONSOLE_TAG_FILTER_INFO => Some(ConsoleAction::SetFilter(ConsoleFilterLevel::Info)),
        CONSOLE_TAG_FILTER_DEBUG => Some(ConsoleAction::SetFilter(ConsoleFilterLevel::Debug)),
        CONSOLE_TAG_AUTOSCROLL => Some(ConsoleAction::ToggleAutoScroll),
        CONSOLE_TAG_SEARCH_CLEAR => Some(ConsoleAction::ClearSearch),
        CONSOLE_TAG_SEARCH_INPUT => Some(ConsoleAction::FocusSearch),
        _ => None,
    }
}

/// Evaluates a mouse cursor coordinate against the semantic `UiTree` to resolve toolbar cursor hints.
///
/// Returns `Some(ConsoleToolbarCursor)` if hovering over a recognized console toolbar widget.
pub fn evaluate_console_toolbar_cursor(
    tree: &UiTree,
    cursor_pos: Point,
) -> Option<ConsoleToolbarCursor> {
    let hit = tree.hit_test_target(cursor_pos)?;
    match hit.tag {
        CONSOLE_TAG_CLEAR
        | CONSOLE_TAG_FILTER_ALL
        | CONSOLE_TAG_FILTER_ERROR
        | CONSOLE_TAG_FILTER_WARN
        | CONSOLE_TAG_FILTER_INFO
        | CONSOLE_TAG_FILTER_DEBUG
        | CONSOLE_TAG_AUTOSCROLL
        | CONSOLE_TAG_SEARCH_CLEAR
        | CONSOLE_TAG_SCROLLBAR_TRACK
        | CONSOLE_TAG_SCROLLBAR_THUMB => Some(ConsoleToolbarCursor::Pointer),
        CONSOLE_TAG_SEARCH_INPUT => Some(ConsoleToolbarCursor::Text),
        _ => {
            if hit.role == WidgetRole::Button {
                Some(ConsoleToolbarCursor::Pointer)
            } else {
                None
            }
        }
    }
}

/// Parameters passed to the Developer Console layout builder.
pub struct ConsolePanelParams<'a> {
    /// Bounding rectangle allocated for the docked console panel.
    pub panel_rect: Rect,
    /// Slice of active in-memory log entries.
    pub entries: &'a [ConsoleEntry],
    /// Current vertical scroll offset in physical pixels.
    pub scroll_y: f32,
    /// Active log severity filter.
    pub filter: ConsoleFilterLevel,
    /// Substring search query for filtering log targets and messages.
    pub search_query: &'a str,
    /// Whether the console automatically scrolls down when new logs arrive.
    pub auto_scroll: bool,
    /// Current cursor position for hover detection.
    pub cursor_pos: Point,
    /// Caret blink phase indicator for text inputs.
    pub blink_caret: bool,
    /// Whether the scrollbar thumb is currently being dragged.
    pub is_scrollbar_dragging: bool,
}

/// Persistent interactive state for the Developer Console panel overlay.
#[derive(Debug, Clone)]
pub struct ConsolePanelState {
    /// Common panel interaction state (scroll_y, search, actions).
    pub interactions: crate::ui::iris_bridge::types::PanelInteractionState<(), ConsoleAction>,
    /// Active log level severity filter.
    pub filter: ConsoleFilterLevel,
    /// Whether Developer Console automatically scrolls down when new logs arrive.
    pub auto_scroll: bool,
    /// Maximum vertical scroll limit computed during layout.
    pub max_scroll_y: f32,
    /// Active scrollbar dragging state: `(start_cursor_y, start_scroll_y)`.
    pub active_scrollbar_drag: Option<(f32, f32)>,
    /// Active screen bounding rectangle of the Developer Console panel.
    pub panel_rect: Option<irisui::prelude::Rect>,
    /// Last recorded log entries count for detecting new incoming console logs.
    pub last_entries_count: usize,
    /// Last recorded log severity filter level.
    pub last_filter: ConsoleFilterLevel,
}

impl Default for ConsolePanelState {
    fn default() -> Self {
        Self {
            interactions: crate::ui::iris_bridge::types::PanelInteractionState::default(),
            filter: ConsoleFilterLevel::All,
            auto_scroll: true,
            max_scroll_y: 0.0,
            active_scrollbar_drag: None,
            panel_rect: None,
            last_entries_count: 0,
            last_filter: ConsoleFilterLevel::All,
        }
    }
}

impl std::ops::Deref for ConsolePanelState {
    type Target = crate::ui::iris_bridge::types::PanelInteractionState<(), ConsoleAction>;
    fn deref(&self) -> &Self::Target {
        &self.interactions
    }
}

impl std::ops::DerefMut for ConsolePanelState {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.interactions
    }
}

/// Semantic alias for [`ConsolePanelState`].
pub type ConsoleState = ConsolePanelState;

impl ConsolePanelState {
    /// Evaluates whether the Developer Console panel requires an in-place repaint.
    ///
    /// Inspects whether new log entries arrived, logs were cleared, or the active
    /// log severity filter changed.
    pub fn is_dirty(
        &self,
        params: &crate::ui::iris_bridge::types::OverlayUpdateParams<'_>,
    ) -> bool {
        self.last_entries_count != params.panel_data.console_entries.len()
            || self.last_filter != self.filter
    }

    /// Synchronizes internal cached snapshot values against active frame parameters.
    pub fn sync_dirty(&mut self, params: &crate::ui::iris_bridge::types::OverlayUpdateParams<'_>) {
        self.last_entries_count = params.panel_data.console_entries.len();
        self.last_filter = self.filter;
    }

    /// Evaluates `is_dirty` and automatically updates snapshot caches if dirty.
    ///
    /// Returns `true` if the panel state changed and requires redraw tagging.
    pub fn check_and_sync_dirty(
        &mut self,
        params: &crate::ui::iris_bridge::types::OverlayUpdateParams<'_>,
    ) -> bool {
        let dirty = self.is_dirty(params);
        if dirty {
            self.sync_dirty(params);
        }
        dirty
    }
}