[package]
name = "ae_launcher"
version = "0.1.0"
edition = "2024"
authors = ["AethelisDEV <contact@aethelis.dev>"]
description = "Lightweight Project Hub and Dimension Mode Launcher for Aeon Engine."
license = "MPL-2.0"

[dependencies]
irisui = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
image = "0.25.10"
rfd = "0.17.2"
