// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 AethelisDEV / Aeon Engine. All rights reserved.

//! # Console Types, Semantic Tags & Hit-Testing (`iris-widgets::console::types`)
//!
//! Provides semantic hit-testing tags, severity filter levels, actions, and cursor resolvers
//! for the Developer Console in Iris UI.
//!

use iris_core::WidgetRole;
use iris_core::geometry::Point;
use iris_core::tree::UiTree;

/// Semantic hit-testing tag for the Developer Console root panel container.
pub const CONSOLE_TAG_PANEL_ROOT: u64 = 0x5000;

/// Semantic hit-testing tag for the "Clear Logs" toolbar button.
pub const CONSOLE_TAG_CLEAR: u64 = 0x5001;

/// Semantic hit-testing tag for the "All" severity filter button.
pub const CONSOLE_TAG_FILTER_ALL: u64 = 0x5002;

/// Semantic hit-testing tag for the "Errors" severity filter button.
pub const CONSOLE_TAG_FILTER_ERROR: u64 = 0x5003;

/// Semantic hit-testing tag for the "Warnings" severity filter button.
pub const CONSOLE_TAG_FILTER_WARN: u64 = 0x5004;

/// Semantic hit-testing tag for the "Info" severity filter button.
pub const CONSOLE_TAG_FILTER_INFO: u64 = 0x5005;

/// Semantic hit-testing tag for the "Debug" severity filter button.
pub const CONSOLE_TAG_FILTER_DEBUG: u64 = 0x5006;

/// Semantic hit-testing tag for the "Auto-Scroll" toggle button.
pub const CONSOLE_TAG_AUTOSCROLL: u64 = 0x5007;

/// Semantic hit-testing tag for the search clear "✖" button.
pub const CONSOLE_TAG_SEARCH_CLEAR: u64 = 0x5008;

/// Semantic hit-testing tag for the search text input field.
pub const CONSOLE_TAG_SEARCH_INPUT: u64 = 0x5009;

/// Semantic hit-testing tag for the Developer Console toolbar container.
pub const CONSOLE_TAG_TOOLBAR: u64 = 0x500a;

/// Semantic hit-testing tag for the Developer Console scrollable logs viewport.
pub const CONSOLE_TAG_VIEWPORT: u64 = 0x500b;

/// Semantic hit-testing tag for individual Developer Console log entry rows.
pub const CONSOLE_TAG_ROW: u64 = 0x500c;

/// Semantic hit-testing tag for the Developer Console scrollbar track.
pub const CONSOLE_TAG_SCROLLBAR_TRACK: u64 = 0x500d;

/// Semantic hit-testing tag for the Developer Console scrollbar thumb.
pub const CONSOLE_TAG_SCROLLBAR_THUMB: u64 = 0x500e;

/// Determines whether the given semantic hit-testing tag belongs to the Developer Console subsystem.
///
/// Returns `true` if `tag` falls within the Developer Console tag range (`0x5000..=0x50ff`).
#[inline]
#[must_use]
pub const fn is_console_tag(tag: u64) -> bool {
    tag >= 0x5000 && tag <= 0x50ff
}

/// Log severity filter levels supported by the Developer Console.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum ConsoleFilterLevel {
    /// Display all log messages without severity filtering.
    #[default]
    All,
    /// Display only error messages.
    Error,
    /// Display only warning messages.
    Warn,
    /// Display only informational messages.
    Info,
    /// Display only debug messages.
    Debug,
}

impl ConsoleFilterLevel {
    /// Returns the human-readable display label for the filter button.
    #[must_use]
    pub const fn label(&self) -> &'static str {
        match self {
            Self::All => "All",
            Self::Error => "Errors",
            Self::Warn => "Warnings",
            Self::Info => "Info",
            Self::Debug => "Debug",
        }
    }
}

/// Actions generated by user interaction with the Developer Console toolbar.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConsoleToolbarAction {
    /// Request clearing all stored log entries.
    ClearLogs,
    /// Request switching the active log severity filter.
    SetFilter(ConsoleFilterLevel),
    /// Request toggling automatic scrolling when new logs arrive.
    ToggleAutoScroll,
    /// Request focusing the text search query input.
    FocusSearch,
    /// Request clearing the active text search filter query.
    ClearSearch,
}

/// Cursor icon hints for console interactive hover targets.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConsoleToolbarCursor {
    /// Interactive click target (button, filter tab, clear toggle).
    Pointer,
    /// Editable text input field.
    Text,
}

/// Severity level representation for individual console log entries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum ConsoleLogLevel {
    /// Severe error condition or unrecoverable subsystem failure.
    Error,
    /// Non-fatal warning or unexpected state.
    Warn,
    /// Informational status milestone or progress message.
    #[default]
    Info,
    /// Detailed diagnostic debug trace.
    Debug,
    /// Fine-grained internal execution trace.
    Trace,
}

/// Aggregated log entry counts per severity level for display in toolbar badges.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ConsoleLogCounts {
    /// Total count of all log entries across all severity levels.
    pub all: usize,
    /// Count of log entries with `Error` severity.
    pub error: usize,
    /// Count of log entries with `Warn` severity.
    pub warn: usize,
    /// Count of log entries with `Info` severity.
    pub info: usize,
    /// Count of log entries with `Debug` or `Trace` severity.
    pub debug: usize,
}

impl ConsoleLogCounts {
    /// Creates a new log count descriptor with all fields explicitly initialized.
    #[inline]
    #[must_use]
    pub const fn new(all: usize, error: usize, warn: usize, info: usize, debug: usize) -> Self {
        Self {
            all,
            error,
            warn,
            info,
            debug,
        }
    }
}

/// Evaluates a mouse click coordinate against the semantic `UiTree` to resolve console toolbar actions.
///
/// Returns `Some(ConsoleToolbarAction)` if the click position hits a recognized console toolbar element.
pub fn evaluate_console_toolbar_click(
    tree: &UiTree,
    click_pos: Point,
) -> Option<ConsoleToolbarAction> {
    let hit = tree.hit_test_target(click_pos)?;
    match hit.tag {
        CONSOLE_TAG_CLEAR => Some(ConsoleToolbarAction::ClearLogs),
        CONSOLE_TAG_FILTER_ALL => Some(ConsoleToolbarAction::SetFilter(ConsoleFilterLevel::All)),
        CONSOLE_TAG_FILTER_ERROR => {
            Some(ConsoleToolbarAction::SetFilter(ConsoleFilterLevel::Error))
        }
        CONSOLE_TAG_FILTER_WARN => Some(ConsoleToolbarAction::SetFilter(ConsoleFilterLevel::Warn)),
        CONSOLE_TAG_FILTER_INFO => Some(ConsoleToolbarAction::SetFilter(ConsoleFilterLevel::Info)),
        CONSOLE_TAG_FILTER_DEBUG => {
            Some(ConsoleToolbarAction::SetFilter(ConsoleFilterLevel::Debug))
        }
        CONSOLE_TAG_AUTOSCROLL => Some(ConsoleToolbarAction::ToggleAutoScroll),
        CONSOLE_TAG_SEARCH_CLEAR => Some(ConsoleToolbarAction::ClearSearch),
        CONSOLE_TAG_SEARCH_INPUT => Some(ConsoleToolbarAction::FocusSearch),
        _ => None,
    }
}

/// Evaluates a mouse cursor coordinate against the semantic `UiTree` to resolve toolbar cursor hints.
///
/// Returns `Some(ConsoleToolbarCursor)` if hovering over a recognized console toolbar widget.
pub fn evaluate_console_toolbar_cursor(
    tree: &UiTree,
    cursor_pos: Point,
) -> Option<ConsoleToolbarCursor> {
    let hit = tree.hit_test_target(cursor_pos)?;
    match hit.tag {
        CONSOLE_TAG_CLEAR
        | CONSOLE_TAG_FILTER_ALL
        | CONSOLE_TAG_FILTER_ERROR
        | CONSOLE_TAG_FILTER_WARN
        | CONSOLE_TAG_FILTER_INFO
        | CONSOLE_TAG_FILTER_DEBUG
        | CONSOLE_TAG_AUTOSCROLL
        | CONSOLE_TAG_SEARCH_CLEAR
        | CONSOLE_TAG_SCROLLBAR_TRACK
        | CONSOLE_TAG_SCROLLBAR_THUMB => Some(ConsoleToolbarCursor::Pointer),
        CONSOLE_TAG_SEARCH_INPUT => Some(ConsoleToolbarCursor::Text),
        _ => {
            if hit.role == WidgetRole::Button {
                Some(ConsoleToolbarCursor::Pointer)
            } else {
                None
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use iris_core::geometry::Rect;

    #[test]
    fn test_console_filter_level_labels() {
        assert_eq!(ConsoleFilterLevel::All.label(), "All");
        assert_eq!(ConsoleFilterLevel::Error.label(), "Errors");
        assert_eq!(ConsoleFilterLevel::Warn.label(), "Warnings");
        assert_eq!(ConsoleFilterLevel::Info.label(), "Info");
        assert_eq!(ConsoleFilterLevel::Debug.label(), "Debug");
    }

    #[test]
    fn test_console_toolbar_hit_testing() {
        let mut tree = UiTree::new();
        let root = tree.create_root().expect("Root node creation");

        // Clear button
        let clear_id = tree.create_node();
        if let Some(node) = tree.get_mut(clear_id) {
            node.computed_rect = Rect::new(10.0, 10.0, 50.0, 24.0);
            node.tag = CONSOLE_TAG_CLEAR;
            node.role = WidgetRole::Button;
        }
        let _ = tree.add_child(root, clear_id);

        // Error filter button
        let error_id = tree.create_node();
        if let Some(node) = tree.get_mut(error_id) {
            node.computed_rect = Rect::new(70.0, 10.0, 50.0, 24.0);
            node.tag = CONSOLE_TAG_FILTER_ERROR;
            node.role = WidgetRole::Button;
        }
        let _ = tree.add_child(root, error_id);

        // Search Input
        let search_id = tree.create_node();
        if let Some(node) = tree.get_mut(search_id) {
            node.computed_rect = Rect::new(130.0, 10.0, 100.0, 24.0);
            node.tag = CONSOLE_TAG_SEARCH_INPUT;
            node.role = WidgetRole::Default;
        }
        let _ = tree.add_child(root, search_id);

        // Outside click
        assert_eq!(
            evaluate_console_toolbar_click(&tree, Point::new(0.0, 0.0)),
            None
        );
        assert_eq!(
            evaluate_console_toolbar_cursor(&tree, Point::new(0.0, 0.0)),
            None
        );

        // Clear click
        assert_eq!(
            evaluate_console_toolbar_click(&tree, Point::new(25.0, 15.0)),
            Some(ConsoleToolbarAction::ClearLogs)
        );
        assert_eq!(
            evaluate_console_toolbar_cursor(&tree, Point::new(25.0, 15.0)),
            Some(ConsoleToolbarCursor::Pointer)
        );

        // Error click
        assert_eq!(
            evaluate_console_toolbar_click(&tree, Point::new(85.0, 15.0)),
            Some(ConsoleToolbarAction::SetFilter(ConsoleFilterLevel::Error))
        );
        assert_eq!(
            evaluate_console_toolbar_cursor(&tree, Point::new(85.0, 15.0)),
            Some(ConsoleToolbarCursor::Pointer)
        );

        // Search Input click & cursor
        assert_eq!(
            evaluate_console_toolbar_click(&tree, Point::new(150.0, 15.0)),
            Some(ConsoleToolbarAction::FocusSearch)
        );
        assert_eq!(
            evaluate_console_toolbar_cursor(&tree, Point::new(150.0, 15.0)),
            Some(ConsoleToolbarCursor::Text)
        );
    }
}