// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 AethelisDEV / Aeon Engine. All rights reserved.

//! Standardized combobox property row widget for inspectors and forms.
//!
//! Organizes a left-aligned property label, an interactive combobox pill button,
//! and an optional adjacent side action button (e.g. `[ ↺ Preset ]`) within a single horizontal row.

use crate::dropdown::button::{ComboboxButtonBuilder, ComboboxButtonFrame, ComboboxButtonStyle};
use iris_core::color::Color;
use iris_core::geometry::{Point, Rect};
use iris_core::id::WidgetId;
use iris_core::node::WidgetRole;
use iris_core::style::{Style, TextAlign};
use iris_core::tree::UiTree;

/// Visual theme and metrics configuration for combobox property rows.
#[derive(Debug, Clone)]
pub struct ComboboxRowStyle {
    /// Text color for the leading property name label.
    pub label_color: Color,
    /// Font size for the leading property name label.
    pub label_font_size: f32,
    /// Visual style applied to the combobox pill button.
    pub button_style: ComboboxButtonStyle,
    /// Background color of the side action button in the idle state.
    pub action_bg_idle: Color,
    /// Background color of the side action button when hovered.
    pub action_bg_hover: Color,
    /// Border stroke color of the side action button.
    pub action_border: Color,
    /// Text color of the side action button in the idle state.
    pub action_text_idle: Color,
    /// Text color of the side action button when hovered.
    pub action_text_hover: Color,
    /// Font size for the side action button label.
    pub action_font_size: f32,
    /// Horizontal gap between the label and the combobox pill.
    pub gap_label_combo: f32,
    /// Horizontal gap between the combobox pill and the side action button.
    pub gap_combo_action: f32,
}

impl Default for ComboboxRowStyle {
    fn default() -> Self {
        Self {
            label_color: Color::rgba(0.620, 0.635, 0.678, 1.0),
            label_font_size: 11.0,
            button_style: ComboboxButtonStyle::default(),
            action_bg_idle: Color::rgba(0.157, 0.165, 0.188, 0.98),
            action_bg_hover: Color::rgba(0.200, 0.208, 0.235, 1.0),
            action_border: Color::rgba(0.212, 0.220, 0.259, 0.85),
            action_text_idle: Color::rgba(0.82, 0.84, 0.88, 1.0),
            action_text_hover: Color::WHITE,
            action_font_size: 10.5,
            gap_label_combo: 4.0,
            gap_combo_action: 6.0,
        }
    }
}

/// Layout and node identifiers generated by building a combobox property row.
#[derive(Debug, Clone, PartialEq)]
pub struct ComboboxRowFrame {
    /// Generational node identifier for the leading text label.
    pub label_id: WidgetId,
    /// Layout frame of the instantiated combobox pill button.
    pub combo_frame: ComboboxButtonFrame,
    /// Node identifier for the optional side action button, if configured.
    pub action_btn_id: Option<WidgetId>,
    /// Bounding rectangle for the optional side action button, if configured.
    pub action_btn_rect: Option<Rect>,
}

/// Fluent builder for constructing standardized inspector combobox rows.
#[derive(Debug, Clone)]
pub struct ComboboxRowBuilder<'a> {
    origin: Point,
    row_height: f32,
    label_text: &'a str,
    label_width: f32,
    combo_width: f32,
    selected_text: &'a str,
    is_open: bool,
    cursor_pos: Point,
    action_btn: Option<(&'a str, f32)>,
    combo_tag: Option<u64>,
    action_tag: Option<u64>,
    style: ComboboxRowStyle,
    name: String,
}

impl<'a> ComboboxRowBuilder<'a> {
    /// Creates a new combobox row builder at the specified top-left coordinate.
    #[inline]
    pub fn new(x: f32, y: f32, row_height: f32) -> Self {
        Self {
            origin: Point::new(x, y),
            row_height,
            label_text: "",
            label_width: 85.0,
            combo_width: 88.0,
            selected_text: "",
            is_open: false,
            cursor_pos: Point::new(-1000.0, -1000.0),
            action_btn: None,
            combo_tag: None,
            action_tag: None,
            style: ComboboxRowStyle::default(),
            name: "ComboboxRow".to_string(),
        }
    }

    /// Sets the leading property text label and its reserved width in logical pixels.
    #[inline]
    pub fn label(mut self, text: &'a str, width: f32) -> Self {
        self.label_text = text;
        self.label_width = width;
        self
    }

    /// Sets the width and currently displayed selection text for the combobox pill button.
    #[inline]
    pub fn combo(mut self, width: f32, selected_text: &'a str) -> Self {
        self.combo_width = width;
        self.selected_text = selected_text;
        self
    }

    /// Sets whether the combobox dropdown menu is actively open.
    #[inline]
    pub fn is_open(mut self, is_open: bool) -> Self {
        self.is_open = is_open;
        self
    }

    /// Supplies the active mouse cursor position for hover evaluation across all interactive elements.
    #[inline]
    pub fn cursor_pos(mut self, cursor_pos: Point) -> Self {
        self.cursor_pos = cursor_pos;
        self
    }

    /// Configures an optional trailing action button (e.g. `[ ↺ Preset ]`) with custom width.
    #[inline]
    pub fn action_button(mut self, text: &'a str, width: f32) -> Self {
        self.action_btn = Some((text, width));
        self
    }

    /// Assigns a semantic identifier tag to the combobox button node (`node.tag`).
    #[inline]
    pub fn combo_tag(mut self, tag: u64) -> Self {
        self.combo_tag = Some(tag);
        self
    }

    /// Assigns a semantic identifier tag to the side action button node (`node.tag`).
    #[inline]
    pub fn action_tag(mut self, tag: u64) -> Self {
        self.action_tag = Some(tag);
        self
    }

    /// Overrides the visual styling configuration for the combobox row.
    #[inline]
    pub fn style(mut self, style: ComboboxRowStyle) -> Self {
        self.style = style;
        self
    }

    /// Sets a descriptive debug name for the generated widget nodes.
    #[inline]
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.name = name.into();
        self
    }

    /// Builds the complete combobox row hierarchy into the target [`UiTree`].
    pub fn build(self, tree: &mut UiTree, parent_id: WidgetId) -> ComboboxRowFrame {
        // 1. Property Name Label
        let label_rect = Rect::new(
            self.origin.x,
            self.origin.y,
            self.label_width,
            self.row_height,
        );
        let label_id = tree.create_node();
        if let Some(node) = tree.get_mut(label_id) {
            node.set_name(format!("{}_Label", self.name));
            node.set_role(WidgetRole::Default);
            node.computed_rect = label_rect;
            node.set_text(self.label_text);
            node.font_size = self.style.label_font_size;
            node.line_height = self.row_height;
            node.text_align = TextAlign::Left;
            node.text_color = self.style.label_color;
        }
        let _ = tree.add_child(parent_id, label_id);

        // 2. Combobox Pill Button
        let combo_x = self.origin.x + self.label_width + self.style.gap_label_combo;
        let combo_rect = Rect::new(combo_x, self.origin.y, self.combo_width, self.row_height);

        let mut button_builder = ComboboxButtonBuilder::new(combo_rect)
            .name(format!("{}_Pill", self.name))
            .selected_text(self.selected_text)
            .is_open(self.is_open)
            .cursor_pos(self.cursor_pos)
            .style(self.style.button_style);

        if let Some(tag_val) = self.combo_tag {
            button_builder = button_builder.tag(tag_val);
        }

        let combo_frame = button_builder.build(tree, parent_id);

        // 3. Optional Trailing Action Button
        let mut action_btn_id = None;
        let mut action_btn_rect = None;

        if let Some((btn_label, btn_w)) = self.action_btn {
            let btn_x = combo_rect.right() + self.style.gap_combo_action;
            let b_rect = Rect::new(btn_x, self.origin.y, btn_w, self.row_height);
            let is_hovered = b_rect.contains_point(self.cursor_pos);

            let btn_id = tree.create_node();
            if let Some(node) = tree.get_mut(btn_id) {
                node.set_name(format!("{}_ActionBtn", self.name));
                node.set_role(WidgetRole::Button);
                node.computed_rect = b_rect;
                if let Some(tag_val) = self.action_tag {
                    node.set_tag(tag_val);
                }

                let bg = if is_hovered {
                    self.style.action_bg_hover
                } else {
                    self.style.action_bg_idle
                };
                let text_col = if is_hovered {
                    self.style.action_text_hover
                } else {
                    self.style.action_text_idle
                };

                node.style = Style::new()
                    .background(bg)
                    .border(1.0, self.style.action_border)
                    .border_radius(5.0);
                node.set_text(btn_label);
                node.font_size = self.style.action_font_size;
                node.line_height = self.row_height;
                node.text_align = TextAlign::Center;
                node.text_color = text_col;
            }
            let _ = tree.add_child(parent_id, btn_id);

            action_btn_id = Some(btn_id);
            action_btn_rect = Some(b_rect);
        }

        ComboboxRowFrame {
            label_id,
            combo_frame,
            action_btn_id,
            action_btn_rect,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_combobox_row_builder_standard() {
        let mut tree = UiTree::new();
        let root = tree.create_node();

        let frame = ComboboxRowBuilder::new(10.0, 50.0, 22.0)
            .label("Shape:", 80.0)
            .combo(88.0, "Capsule")
            .is_open(false)
            .combo_tag(100)
            .build(&mut tree, root);

        assert_eq!(frame.combo_frame.button_rect.x, 10.0 + 80.0 + 4.0);
        assert_eq!(frame.combo_frame.button_rect.width, 88.0);
        assert!(frame.action_btn_id.is_none());

        let label_node = tree.get(frame.label_id).unwrap();
        assert_eq!(label_node.text.as_deref(), Some("Shape:"));
    }

    #[test]
    fn test_combobox_row_builder_with_action_button() {
        let mut tree = UiTree::new();
        let root = tree.create_node();

        let frame = ComboboxRowBuilder::new(10.0, 50.0, 22.0)
            .label("Material:", 85.0)
            .combo(80.0, "Default")
            .action_button("↺ Preset", 58.0)
            .combo_tag(101)
            .action_tag(102)
            .build(&mut tree, root);

        assert!(frame.action_btn_id.is_some());
        let action_rect = frame.action_btn_rect.unwrap();
        assert_eq!(action_rect.width, 58.0);
        assert_eq!(action_rect.x, frame.combo_frame.button_rect.right() + 6.0);

        let action_node = tree.get(frame.action_btn_id.unwrap()).unwrap();
        assert_eq!(action_node.role, WidgetRole::Button);
        assert_eq!(action_node.tag, 102);
        assert_eq!(action_node.text.as_deref(), Some("↺ Preset"));
    }
}